security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: argon2i
            memory_cost: 1024 # Amount in KiB. 16 MiB
            time_cost:            2 # Number of iterations
            threads:              2 # Number of parallel threads
    role_hierarchy:
        ROLE_DOCTOR: ROLE_USER
        ROLE_COLLABORATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_DOCTOR, ROLE_COLLABORATOR]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
            access_denied_handler: App\Security\AccessDeniedHandler
            logout: true
            anonymous:    true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN}
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/patient/, role: ROLE_DOCTOR }
        - { path: ^/consultation/, role: ROLE_DOCTOR }
        - { path: ^/appointment/, role: [ROLE_COLLABORATOR , ROLE_DOCTOR] }