easy_admin:
    site_name: '<img src=" /images/innov-med.jpg " style="width:25%; height:100px" alt="logo"/>'
    user:
        display_name: true
        name_property_path: 'username'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'




